//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PrimaryGunHand : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Fire
        {
            get
            {
                return SteamVR_Actions.primaryGunHand_Fire;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchTrigger
        {
            get
            {
                return SteamVR_Actions.primaryGunHand_TouchTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single SqueezeTrigger
        {
            get
            {
                return SteamVR_Actions.primaryGunHand_SqueezeTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean AmmoRelease
        {
            get
            {
                return SteamVR_Actions.primaryGunHand_AmmoRelease;
            }
        }
    }
}
